[package]
name = "rivlib"
version = "0.3.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
failure = "0.1"
scanifc-sys = { path = "scanifc-sys" }
scanlib = { path = "scanlib" }

[workspace]
members = ["scanifc-sys", "scanlib"]
