[package]
name = "scanifc"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
libc = "0.2"
quick-error = "1.2"
scanifc-sys = { path = "../scanifc-sys" }

[dev-dependencies]
tempfile = "2.1"
