[package]
name = "scanlib"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]

[dependencies]
quick-error = "1.2"

[dev-dependencies]
approx = "0.1"

[build-dependencies]
cc = "1.0"
