[package]
name = "scanlib"
version = "0.1.0"
authors = ["Pete Gadomski <pete.gadomski@gmail.com>"]
description = "Custom C++ interface between Rust and Riegl's C++ scanlib"
license = "MIT"

[dependencies]
failure = "0.1"
libc = "0.2"

[build-dependencies]
cc = "1.0"
